USE [REHAB]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVINSPTYPEOBSEV]    Script Date: 7/26/2019 9:02:30 AM ******/
DROP SYNONYM [dbo].[HA8_STMNSERVINSPTYPEOBSEV]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVINSPTYPEOBSEV]    Script Date: 7/26/2019 9:02:30 AM ******/
CREATE SYNONYM [dbo].[HA8_STMNSERVINSPTYPEOBSEV] FOR [HANSEN8].[ASSETMANAGEMENT_STORM].[STMNSERVINSPTYPEOBSEV]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVINSPTYPEOB]    Script Date: 7/26/2019 9:02:26 AM ******/
DROP SYNONYM [dbo].[HA8_STMNSERVINSPTYPEOB]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVINSPTYPEOB]    Script Date: 7/26/2019 9:02:26 AM ******/
CREATE SYNONYM [dbo].[HA8_STMNSERVINSPTYPEOB] FOR [HANSEN8].[ASSETMANAGEMENT_STORM].[STMNSERVINSPTYPEOB]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVINSPOB]    Script Date: 7/26/2019 9:02:21 AM ******/
DROP SYNONYM [dbo].[HA8_STMNSERVINSPOB]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVINSPOB]    Script Date: 7/26/2019 9:02:21 AM ******/
CREATE SYNONYM [dbo].[HA8_STMNSERVINSPOB] FOR [HANSEN8].[ASSETMANAGEMENT_STORM].[STMNSERVINSPOB]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVICEINSP]    Script Date: 7/26/2019 9:02:15 AM ******/
DROP SYNONYM [dbo].[HA8_STMNSERVICEINSP]
GO

/****** Object:  Synonym [dbo].[HA8_STMNSERVICEINSP]    Script Date: 7/26/2019 9:02:15 AM ******/
CREATE SYNONYM [dbo].[HA8_STMNSERVICEINSP] FOR [HANSEN8].[ASSETMANAGEMENT_STORM].[STMNSERVICEINSP]
GO

/****** Object:  Synonym [dbo].[HA8_STMNINDHIST]    Script Date: 7/26/2019 9:02:10 AM ******/
DROP SYNONYM [dbo].[HA8_STMNINDHIST]
GO

/****** Object:  Synonym [dbo].[HA8_STMNINDHIST]    Script Date: 7/26/2019 9:02:10 AM ******/
CREATE SYNONYM [dbo].[HA8_STMNINDHIST] FOR [HANSEN8].[ASSETMANAGEMENT_STORM].[STMNINDHIST]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVINSPTYPEOBSEV]    Script Date: 7/26/2019 9:02:06 AM ******/
DROP SYNONYM [dbo].[HA8_SMNSERVINSPTYPEOBSEV]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVINSPTYPEOBSEV]    Script Date: 7/26/2019 9:02:06 AM ******/
CREATE SYNONYM [dbo].[HA8_SMNSERVINSPTYPEOBSEV] FOR [HANSEN8].[ASSETMANAGEMENT_SEWER].[SMNSERVINSPTYPEOBSEV]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVINSPTYPEOB]    Script Date: 7/26/2019 9:02:01 AM ******/
DROP SYNONYM [dbo].[HA8_SMNSERVINSPTYPEOB]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVINSPTYPEOB]    Script Date: 7/26/2019 9:02:01 AM ******/
CREATE SYNONYM [dbo].[HA8_SMNSERVINSPTYPEOB] FOR [HANSEN8].[ASSETMANAGEMENT_SEWER].[SMNSERVINSPTYPEOB]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVINSPOB]    Script Date: 7/26/2019 9:01:56 AM ******/
DROP SYNONYM [dbo].[HA8_SMNSERVINSPOB]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVINSPOB]    Script Date: 7/26/2019 9:01:56 AM ******/
CREATE SYNONYM [dbo].[HA8_SMNSERVINSPOB] FOR [HANSEN8].[ASSETMANAGEMENT_SEWER].[SMNSERVINSPOB]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVICEINSP]    Script Date: 7/26/2019 9:01:52 AM ******/
DROP SYNONYM [dbo].[HA8_SMNSERVICEINSP]
GO

/****** Object:  Synonym [dbo].[HA8_SMNSERVICEINSP]    Script Date: 7/26/2019 9:01:52 AM ******/
CREATE SYNONYM [dbo].[HA8_SMNSERVICEINSP] FOR [HANSEN8].[ASSETMANAGEMENT_SEWER].[SMNSERVICEINSP]
GO

/****** Object:  Synonym [dbo].[HA8_SMNINDHIST]    Script Date: 7/26/2019 9:01:47 AM ******/
DROP SYNONYM [dbo].[HA8_SMNINDHIST]
GO

/****** Object:  Synonym [dbo].[HA8_SMNINDHIST]    Script Date: 7/26/2019 9:01:47 AM ******/
CREATE SYNONYM [dbo].[HA8_SMNINDHIST] FOR [HANSEN8].[ASSETMANAGEMENT_SEWER].[SMNINDHIST]
GO

/****** Object:  Synonym [dbo].[HA8_COPSTORMMAIN]    Script Date: 7/26/2019 9:01:43 AM ******/
DROP SYNONYM [dbo].[HA8_COPSTORMMAIN]
GO

/****** Object:  Synonym [dbo].[HA8_COPSTORMMAIN]    Script Date: 7/26/2019 9:01:43 AM ******/
CREATE SYNONYM [dbo].[HA8_COPSTORMMAIN] FOR [HANSEN8].[COPASSETMANAGEMENTSTORM].[COPSTORMMAIN]
GO

/****** Object:  Synonym [dbo].[HA8_COPSTMNALTGRD]    Script Date: 7/26/2019 9:01:37 AM ******/
DROP SYNONYM [dbo].[HA8_COPSTMNALTGRD]
GO

/****** Object:  Synonym [dbo].[HA8_COPSTMNALTGRD]    Script Date: 7/26/2019 9:01:37 AM ******/
CREATE SYNONYM [dbo].[HA8_COPSTMNALTGRD] FOR [HANSEN8].[COPASSETMANAGEMENTSTORM].[COPSTMNALTGRD]
GO

/****** Object:  Synonym [dbo].[HA8_COMPTYPE]    Script Date: 7/26/2019 9:01:32 AM ******/
DROP SYNONYM [dbo].[HA8_COMPTYPE]
GO

/****** Object:  Synonym [dbo].[HA8_COMPTYPE]    Script Date: 7/26/2019 9:01:32 AM ******/
CREATE SYNONYM [dbo].[HA8_COMPTYPE] FOR [HANSEN8].[ASSETMANAGEMENT].[COMPTYPE]
GO

/****** Object:  Synonym [dbo].[HA8_COMPSTMN]    Script Date: 7/26/2019 9:01:26 AM ******/
DROP SYNONYM [dbo].[HA8_COMPSTMN]
GO

/****** Object:  Synonym [dbo].[HA8_COMPSTMN]    Script Date: 7/26/2019 9:01:26 AM ******/
CREATE SYNONYM [dbo].[HA8_COMPSTMN] FOR [HANSEN8].[ASSETMANAGEMENT_STORM].[COMPSTMN]
GO

/****** Object:  Synonym [dbo].[HA8_COMPSMN]    Script Date: 7/26/2019 9:01:02 AM ******/
DROP SYNONYM [dbo].[HA8_COMPSMN]
GO

/****** Object:  Synonym [dbo].[HA8_COMPSMN]    Script Date: 7/26/2019 9:01:02 AM ******/
CREATE SYNONYM [dbo].[HA8_COMPSMN] FOR [HANSEN8].[ASSETMANAGEMENT_SEWER].[COMPSMN]
GO

/****** Object:  Synonym [dbo].[HA8_ASSETINSPINDEX]    Script Date: 7/26/2019 9:00:53 AM ******/
DROP SYNONYM [dbo].[HA8_ASSETINSPINDEX]
GO

/****** Object:  Synonym [dbo].[HA8_ASSETINSPINDEX]    Script Date: 7/26/2019 9:00:54 AM ******/
CREATE SYNONYM [dbo].[HA8_ASSETINSPINDEX] FOR [HANSEN8].[ASSETMANAGEMENT].[ASSETINSPINDEX]
GO

